name: Tag
on: 
  create:
    tags:
      - v*
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source code
      uses: actions/checkout@v1
    - name: Get Branch
      run: |
        raw=$(git branch --contains ${{ github.ref }} | grep -v "*" | tr -d '[:space:]')
        echo $raw
        branch=${raw:2}
        echo $branch
        echo '::set-env name=BRANCH::$branch'
    - run: echo ${{ env.BRANCH }}