name: Tag
on: 
  create:
    tags:
      - v*
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source code
      uses: actions/checkout@v1
    - name: Get Branch
      run: |
        raw=$(git branch --contains ${{ github.ref }})
        branch=${raw:2}
    - run: echo $branch